# AppVeyor build configuration
# https://www.appveyor.com/docs/build-configuration
# https://www.appveyor.com/docs/appveyor-yml/
#---------------------------------#
#      general configuration      #
#---------------------------------#
# version format
version: 1.0.{build}-{branch}
image: Visual Studio 2017
# add platforms to build matrix:
platform:
- x64
# add configurations to build matrix:
configuration:
- Release
# use custom build_script
build_script:
- ECHO BUILD %CONFIGURATION% %PLATFORM%
- msbuild /m HelloElfLoader.sln /p:Configuration=%CONFIGURATION% /p:Platform=%PLATFORM%
after_build:
  - 7z a HelloElfLoader.7z "C:\projects\helloelfloader\x64\Release\HelloElfLoader.exe"

artifacts:  # Archive the generated packages in the ci.appveyor.com build report.  - path: bin\Debug\*
  - path: HelloElfLoader.7z
    name: artifacts-all
    
